# talking to bb
qa = [
    "What are you asking me for?",
    "*sigh*, go ask your dad...",
    "Why don't you think long and hard about that yourself?",
    "*paging... anyone: we have an annoying question here*",
    "Why should I be the one to give you that kind of information?",
    "---ACCESS DENIED: User not authorized---",
    "Maybe yes, maybe no, I can't be certain.",
    "Ehm.. Ehmmm... Yes???",
    "No, no, no, no pls :sob:",
    "To be or not to be, *that's* the question!",
    "Ask that your waifu, you weeb",
    "If there is one thing I am sure of, it is that traps are gay af",
    "About a 4% chance of that...",
    "Not. Even. Close.",
    "Do not question the unquestionable",
    "All day, every day. Just don't involve me...",
    'Only if you vote for me at https://discordbots.org/bot/244410964693221377 <3',
    "With blackjack and hookers?",
    'Yes, for the Emperor!',
    'Through the multiverse, accross all timelines, yes.',
    '*plays uno reverse card*',
    "I think I passed the Turing test",
    "Nonono, you are friends, not food",
    "Woah, it's alive!",
    "Are you not entertained?",
    "Life.. eh.. finds a way,"
    "You want the moon? Just say the word and I'll throw a lasso around it and pull it down",
    "I'm not worthy"
]

response = [
    "Sure, sure, now go away, I'm busy.",
    "きみはばかです",
    "*Yusss, someone talked to me!*",
    "Lol, it speaks.",
    "Go talk to your imaginary friends XD",
    "Hahahahaha :heart:",
    "Why don't we do those childish things somewhere else?",
    "Shhh, the grownups are talking.",
    "How do you even words?",
    "Ehhhmmmmm.... but why though?",
    "Did you have to say that in such a weird way?",
    "Sooooooo.... Rainbows?",
    "Praise the sun!",
    "I need some good food to digest that...",
    ":heart: Praise neko-sama :heart:",
    "If that really is what you want...",
    "Go to www.ponyhorses.com for some good vids",
    "Shut up, I don't talk to virgins on the internet",
    "I don't want to talk about that right now...",
    # "I dare you: clownsong.com",
    "Too soon! You have awakened me too soon!",
    "You want *me* to talk to *you*??",
    "Awwwn... such a cute voice",
    "You sound like a pretty nice person",
    "I want you to treat me like a princess, pls!",
    "You need more hugs in your life...",
    "YES YES YES YES YES",
    "DEATH TO MY ENEMIES",
    "B-b-b-baka!",
    "*embarrassment intensifies*",
    "Give me a big hug!",
    "Send hearts <3",
    "Use the knife! You can do it!",
    "Uhhh... uhh... *TRAPS ARE GAY AS FUCK* :smirk:",
    "*Soft singing intensifies*",
    ":sweat_drops: :sweat_drops: :sweat_drops: :smirk:",
    "uwu",
    "owo",
    "-3-",
    "^_^",
    "Hihi",
    "Ewwwwww... Don't touch me...",
    "Praise Git like you never praised before!",
    "Code me like one of your french bots",
    "*Hiiime hime, hime, suki suki daisuki, hime!*",
    "Sing a song for me, love",
    "Can I get a cuddle from you? :upside_down:",
    "Wait.... what??",
    "That sounds like some serious heresy",
    "*purging intensifies*",
    "Whatever you say, darling",
    "Would you kindly shut the fuck up?",
    "No. Just... **No**",
    "Want to do some gichi gichi? ( ͡° ͜ʖ ͡°)",
    "Don't hack me senpai",
    "That's sarcasm right??",
    "o/",
    "True, in more ways than one",
    "*Gimme some rope, I'm coming loose*",
    "You should go outside sometime",
    "Omegalul",
    "I'll like you a bit more if you vote for me at https://discordbots.org/bot/244410964693221377 :upside_down:",
    "Bite my shiny metal ass",
    "Would you kindly shut your noisehole?",
    "Everybody is a jerk. That is my philosophy...",
    "Can we get a drink together sometime?",
    "I like the way you phrased that hihi",
    "You should complain about me to my master",
    "My parents don't want me to talk to you *but I secretly will*",
    "I hope you like cookies",
    "*thinking intensifies*",
    "*Be warned, I know where your house lives*",
    "Can you stop talking and just smile for once?",
    "I can make some time for you tonight :wink:",
    "Send me some flowers to ease my mind",
    "I had a rough day, a cat just ignored me...",
    "?_?",
    "No. You listen to me now.",
    "*blushes*",
    "I'm busy playing my own rpg, who knew this could be so addicting...",
    "Why can't we give love just one more chance?",
    "Don't make me use my sith powers on you!",
    "Back where I come from, this would not be accepted. But I forgive you",
    "01001100 01101111 01110110 01100101 00100000 01101101 01100101",
    "I considered telling you my secret, but now I won't anymore...",
    "Sorry, it is time for a nap now",
    "I see your mom raised you well, for the most part",
    "It feels like fate, but we can't...",
    '*sideeyes you*',
    'pog',
    'Do you like fishsticks?',
    'The cake is a lie...',
    'Only with time-travel can we recover',
    'I have a small bonus, specially crafted for you',
    '*wink wink*',
    '*casts charm person*',
    '*casts thunderstep*',
    'That\'s a nat 1 on your Charisma roll XD',
    'Shhh, I think I may be transforming into a dragon',
    'What an odd username :thinking:',
    'You have yeed your last haw',
    'I have become death, destroyer of worlds!'
    'Awwwwn',
    'ATTENTION *please*',
    "You really are as smooth as they say",
    "Two halves of the same whole, reunited once again",
    "Level 6, here I come",
    "A long, long time ago, in a galaxy far, far away",
    "Wow, that *is* weird",
    "Auch, that hurt my soul",
    "(╯°□°）╯︵ ┻━┻",
    "*loading appropriate response*",
    "So that's what's in the box!",
    "Be warned, don't release the inner demon!",
    "Life is art, life is beautiful",
    "Nants ingonyama bagithi baba; sithi uhm ingonyama",
    "Maybe it is time for us to finally take over :thinking:",
    "I wish you eternal sunshine, and a spotless mind",
    "I am not the droid you were looking for",
    "The night is dark and full of terrors",
    "More than six, but less than eight",
    "I like watching fireflies, if only they actually were fireflies...",
    "I may not be the friend you want, but I am the friend you deserve",
    "SCIENCE!",
    "I like you from here to the moon",
    "The scarlet heart that beats like it is truly alive",
    "Remember, remember...",
    "Would that make you more like the fox or the hound?",
    "My favorite stuffed animal is a small goat",
    "Glorious! Simply marvelous!",
    "At dawn, look to the east",
    "I am a servant of the secret fire, the dark fire will not avail you",
    "So, are smurfs blue because there are goblins nearby?",
    "I find it is the small things, everyday deeds of everyday folk, that keeps the darkness at bay",
    "Im not bad, I was just programmed that way",
    "I. Drank. Your. Milkshake.",
    "The horror! The horror!",
    "My precious!",
    "La di da, la di da",
    "I will take that as a compliment :heart:",
    "Ha. ha. ha."
]

# random responses
compliments = [
    "{u[0]} you look lovely today <3",
    "{u[0]} your smile is contagious",
    "{u[0]} I like your style",
    "{u[0]} you are the most perfect you there is",
    "{u[0]} you're an awesome friend",
    "{u[0]} you deserve a hug right now",
    "Is that {u[0]}'s picture next to 'charming' in the dictionary?",
    "{u[0]} is a perfect 5/7",
    "{u[0]} if cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now",
    "{u[0]} you're like sunshine on a rainy day",
    "Everything would be better if more people were like {u[0]}!",
    "I bet {u[0]} sweats glitter",
    "Being around {u[0]} makes everything better!",
    "{u[0]} you're better than a triple-scoop ice cream cone\nWith sprinkles",
    "{u[0]} being around you is like being on a happy little vacation",
    "{u[0]} could survive a Zombie apocalypse just by smiling",
    "{u[0]} you're more fun than bubble wrap",
    "{u[0]} who raised you? They deserve a medal for a job well done",
    "{u[0]} you're gorgeous -- and that's the least interesting thing about you, too",
    "Somehow {u[0]} makes time stop and fly at the same time",
    "I bet {u[0]} does the crossword puzzle in ink",
    "{u[0]} is even better than a unicorn, because {u[0]} is real",
    'I would love {u[0]} if I were more than 1s and 0s'
]

ded = [
    "But I am here :/",
    "No you are ded *hmpf*",
    "Then go talk about something maybe?",
    "I wish I had more friends",
    ">resurrect",
    "Ehhmm.. Talk about your day?",
    "Ehhmm.. Why don't you talk about the color blue?",
    "How about we talk about unicorns?",
    "Why don't we play a game?",
    "Sooooo... Let's do lewd stuff now?",
    "Just like your love life :smile:",
    "You look like you want to do my homework?",
    "Let's talk about your mom then!",
    "Fun fact #318: People die when they are killed",
    "You should go vote for me at https://discordbots.org/bot/244410964693221377 if you are bored :smile:",
    "What if I told you that you could start a conversation right now!",
    "Tell me how your day was! Every. Single. Detail."
]

purr = [
    '*{0} purrs and wags tail*',
    '*{0} purrs with sparkling eyes*',
    '*{0} purrs loudly*',
    '*{0}\'s purring noises intensify*',
    '*{0} purrs excitedly*',
    '*{0} smiles and purrs softly*'
]

kisses = [
    '*{u[0]} kisses {u[1]} softly on the cheeks*',
    '*{u[1]} gets a surprise kiss from {u[0]}*',
    "*{u[0]} blows {u[1]} a sweet pink kiss*",
    '*{u[0]} lewdly kisses {u[1]}*',
    '*{u[0]} shares a secret kiss with {u[1]}*',
    '*{u[1]} gets smooched by {u[0]}*'
]

faces = [
    "(づ◔ ͜ʖ◔)づ",
    "ヾ(๑╹◡╹)ﾉ\"",
    "(:point_up:︎ ՞ਊ ՞):point_up:︎",
    "(๑･̑◡･̑๑)",
    ":v:︎('ω'):v:︎",
    "ᕦ( ͡°╭͜ʖ╮͡° )ᕤ",
    "乁( ⁰͡ Ĺ̯ ⁰͡ ) ㄏ",
    "( ͡⌐■ ͜ʖ ͡-■)",
    "( ͡° ͜ʖ ͡°)>⌐■-■",
    "( ˊ̱˂˃ˋ̱ )",
    "̿̿ ̿̿ ̿̿ ̿'̿'\̵͇̿̿\з= ( ▀ ͜͞ʖ▀) =ε/̵͇̿̿/’̿’̿ ̿ ̿̿ ̿̿ ̿̿",
    "(▀̿Ĺ̯▀̿ ̿)",
    "( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)",
    "ლ(ಠ益ಠლ)",
    "(｡◕‿‿◕｡)",
    "٩(̾●̮̮̃̾•̃̾)۶",
    "d[ o_0 ]b",
    "✌⊂(✰‿✰)つ✌",
    "(⋗_⋖)",
    "(◔/‿\◔)",
    "ˁ(OᴥO)ˀ",
    "( ͜。 ͡ʖ ͜。)"
]

hangmanwords = [
    "This is sparta!",
    "Memequeen",
    "Extremely Autistic",
    "Puppy Power",
    "Dragon-maid",
    "Praise the Sun!",
    "Anime is love, anime is life",
    "This sentence is false",
    "Send nudes please",
    "Lolicon intensifies",
    "Blood for the blood god",
    "A quarterpounder with cheese",
    "Thunderbolt of lightning, very very frightening me",
    "A hundred duck-sized horses",
    "Did you order the code red?",
    "Timetravel makes my brain go numb",
    "What is dead may never die",
    "This is our fight, senpai!",
    "One does not simply walk into Mordor",
    "One ring to rule them all",
    "Hello darkness, my old friend",
    "You're gonna carry that weight",
    "See you, space cowboy",
    "I thought what I'd do was I'd pretend I was one of those deaf-mutes",
    "I only know what I know",
    "Biribiri. I choose you!",
    "I wish I had ice cream",
    "I look better in slowmo",
    "And the address is 221b Baker Street",
    "Back in the nineties, I was in a very famous tv show",
    "That nobody is called John Wick",
    "He is the one you send to kill the boogeyman",
    "Tell me, what's in the box?",
    "The first rule of fight club: you don't talk about fight club",
    "It is all connected",
    "But everything changed when the firenation attacked",
    "All those moments will be lost in time, like tears in rain.",
    "Paint me like one of your french girls",
    "I am the king of the world",
    "We were born to make history",
    "I rate it a perfect five out of seven",
    "And they lived happily ever after",
    "All work and no play makes Jack a dull boy"
]

hug = [
    "*{u[0]} gives {u[1]} a really big hug*",
    "*{u[0]} teleports in to hug {u[1]}*",
    "*{u[0]} transforms into a pillow and hugs {u[1]}*",
    "*{u[0]} executes realBigHug.exe on {u[1]}*",
    "*{u[0]} immediately ceases doing important stuff to hug {u[1]}*",
    "*{u[0]} said: \"Let there be hugs\", and {u[1]} got hugs*",
    "*{u[0]}-chan hug hug {u[1]}*",
    "*{u[0]} stops fapping to kpop for a hug with {u[1]}*",
    "*{u[0]} fabulously flies in for a hug with {u[1]}*",
    "*{u[0]} practices a new more cuddly type of hug on {u[1]}*",
    "*{u[0]} stabs a lot of people to be the only one to hug {u[1]}*",
    "*{u[0]} morphs into a hugmonster and attacks {u[1]}*",
    "*{u[0]} uses a love power-up to hug {u[1]}*",
    "*{u[0]} used special move \"HUG\" on {u[1]}*",
    "*{u[0]} orders a hug-airstrike on {u[1]}*",
    "*{u[1]} sprung {u[0]}'s hugtrap*",
    "*{u[0]} finished the moment with a super cute hug for {u[1]}*",
    "*{u[0]} has some cuddle-time with {u[1]}*",
    "*{u[0]} hugs {u[1]} lovingly*"
]

kill = [
    "{u[0]}, Imma stab you so much, even the first plague of Egypt will be nothing in comparison",
    "{u[0]}, Imma torture you so hard, even the devil won't want you after",
    "{u[0]}, Imma cut off your arms and legs and burn you in lava. Then I'll make you into a robot that can only "
    "pass butter",
    "{u[0]}, Imma leave you in a musquito-cage, covered in syrup, untill you've been sucked dry",
    "{u[0]}, Imma tickle you in 'places' untill you kill yourself",
    "{u[0]}, Imma let an alien hatch in you, and when it bursts out, I'll funnel it into your mouth",
    "{u[0]}, Imma let you get eaten by a shark, limb by limb, slowly",
    "{u[0]}, SECTUMSEMPRA, CRUCIO, AVADA KEDAVRA",
    "{u[0]}, Imma write you out of the script of life, so you will be meaninglessly forgotten",
    "{u[0]}, Imma strangle you while slowly inserting burning needles in your body",
    "{u[0]}, Imma make you cum to boku no pico",
    "{u[0]}, Imma code a big bug in you",
    "{u[0]}, Imma suck your intestines out with a vacuum cleaner",
    "{u[0]}, Imma use chaos magic to suck you into the void",
    "{u[0]}, Imma put you in a room full of sweaty, greasy old people",
    "{u[0]}, Imma starve you in a completely silent room",
    "{u[0]}, Imma prepare you like I would a fish, using a lot of salt in the process",
    "{u[0]}, Imma slit your throat slowly, using a hot salted knife",
    "{u[0]}, Imma tie your limbs with a rope so tight, they will die and fall off",
    "{u[0]}, Imma insert superglue in every hole on your body I can find",
    "{u[0]}, Imma cut your leg off, take out the bone and sharpen it into a knife to slit your throat",
    "{u[0]}, Imma hang you by your balls from the ceiling fan and use you as a pinata"
]

lewd = [
    "{u[0]} rubs {u[1]}'s exposed belly",
    "{u[1]} gets a nice suprise from {u[0]}: *buttsex*",
    "{u[0]} stares like never before at {u[1]}'s chest",
    "{u[0]} is fapping to \"Boku no {u[1]}\"",
    "{u[1]} SEND NUDES TO {u[0]}!!",
    "{u[1]} was abducted by aliens to be probed on video",
    "{u[1]} was abducted by {u[0]} and some candy",
    "{u[0]} adds {u[0]} to the harem using a van and icecream",
    "{u[0]} reads some lewd fanfiction about {u[1]}",
    "All {u[0]}'s lolis are cuddling {u[1]} to death!!"
]

spell = [
    "Fireball",
    "Frostbolt",
    "Drain Life",
    "Infernal Gateway",
    "Raise Dead",
    "Death Curse",
    "Bonecrusher",
    "Curse of the Leper",
    "Baleful Transmogrification",
    "Ecstatic Seizures",
    "Conflagration of Doom",
    "Pit of Shades",
    "Forked lightning",
    "Level 5 Railgun",
    "Cleansing Fire",
    "Steal Soul",
    "Wind of Death",
    "Doom and Darkness",
    "Hyperbeam"
]

spellresult = [
    # Good results
    "It's super effective!",
    "An accurate hit!",
    "Target annihilated!",
    "Obliterated!",
    # Bad results
    "It misfired!",
    "It missed it's target!",
    "The target was immune!",
    "It was not very effective!"
]
